output "state_bucket_name" {
  description = "Name of the S3 bucket holding Terraform remote state. Pass to the main module via `-backend-config=\"bucket=<this>\"`."
  value       = aws_s3_bucket.state.bucket
}

output "lock_table_name" {
  description = "DynamoDB table that holds Terraform's state locks."
  value       = aws_dynamodb_table.locks.name
}

output "kms_alias" {
  description = "KMS alias guarding the state objects. Backend config key: `kms_key_id`."
  value       = aws_kms_alias.state.name
}

# -----------------------------------------------------------------------------
# Backend config blobs — paste each into the matching file in ../backends/
# (or pipe directly via `terraform output -raw backend_dev > ../backends/dev.s3.tfbackend`).
# These are heredoc strings so they format cleanly when emitted.
# -----------------------------------------------------------------------------

output "backend_dev" {
  description = "Body of ../backends/dev.s3.tfbackend — pipe to file after `terraform apply`."
  value       = <<-EOT
    # Aurion — Terraform backend config (dev)
    # Generated by infrastructure/bootstrap. Regenerate via:
    #   cd infrastructure/bootstrap && terraform output -raw backend_dev > ../backends/dev.s3.tfbackend
    bucket         = "${aws_s3_bucket.state.bucket}"
    dynamodb_table = "${aws_dynamodb_table.locks.name}"
    key            = "aurion/dev/terraform.tfstate"
    region         = "${var.region}"
    encrypt        = true
    kms_key_id     = "${aws_kms_alias.state.name}"
  EOT
}

output "backend_prod" {
  description = "Body of ../backends/prod.s3.tfbackend — pipe to file after `terraform apply`."
  value       = <<-EOT
    # Aurion — Terraform backend config (prod)
    # Generated by infrastructure/bootstrap. Regenerate via:
    #   cd infrastructure/bootstrap && terraform output -raw backend_prod > ../backends/prod.s3.tfbackend
    bucket         = "${aws_s3_bucket.state.bucket}"
    dynamodb_table = "${aws_dynamodb_table.locks.name}"
    key            = "aurion/prod/terraform.tfstate"
    region         = "${var.region}"
    encrypt        = true
    kms_key_id     = "${aws_kms_alias.state.name}"
  EOT
}
