"""scribe-0 (#620) — mode-aware export footer (GS-9 labelling).

Descriptive mode (flag OFF) keeps the exact prior "descriptive record" wording
(byte-identical); Grounded Synthesis Mode labels the note as a source-grounded
AI note so a synthesized note is never shipped mislabelled as descriptive.
"""

from __future__ import annotations

from app.modules.config.schema import AppConfigSchema, FeatureFlagsConfig
from app.modules.export import service as export_service


def _cfg(on: bool) -> AppConfigSchema:
    return AppConfigSchema(
        feature_flags=FeatureFlagsConfig(grounded_synthesis_enabled=on)
    )


def test_footer_descriptive_off_is_byte_identical(monkeypatch):
    monkeypatch.setattr(export_service, "get_config", lambda: _cfg(False))
    assert export_service._export_footer() == (
        "Generated by Aurion Clinical AI. "
        "This document is a descriptive record of the clinical encounter."
    )


def test_footer_grounded_on_is_not_mislabelled_descriptive(monkeypatch):
    monkeypatch.setattr(export_service, "get_config", lambda: _cfg(True))
    footer = export_service._export_footer()
    assert "descriptive record" not in footer
    assert "no diagnostic or interpretive" not in footer
    assert "grounded in a cited source" in footer
    assert "review required" in footer.lower()
