"""Shared logic for vision providers.

All three vision providers (OpenAI, Anthropic, Gemini) use the same system
prompt and build FrameCaption objects the same way.  Provider-specific code
is limited to the HTTP call and response extraction.
"""

from __future__ import annotations

import json
import logging
from typing import Final

from app.core.types import FrameCaption, MaskedFrame, ProviderError, TranscriptSegment

logger = logging.getLogger("aurion.providers.vision.shared")

# Truncated excerpt length for the WARNING log emitted when a provider
# response fails to parse as JSON. Vision responses are model-generated
# descriptive text per VISION_SYSTEM_PROMPT — not user content / PHI —
# but defensively bounded so a runaway provider response can't bloat
# the log line and so we don't accidentally surface a longer suffix
# that could carry a malformed `?key=...` URL fragment.
_PARSE_FAILURE_LOG_LEN: Final[int] = 120

# JSON Schema for the vision caption response. Used by providers that
# support schema-enforced output (Anthropic tool_use, Gemini
# responseSchema). The integration_status is NOT in the schema — that
# field is computed downstream in vision/service.py classify_captions;
# the LLM just describes what it sees.
VISION_RESPONSE_SCHEMA: dict = {
    "type": "object",
    "properties": {
        "description": {"type": "string"},
        "confidence": {
            "type": "string",
            "enum": ["high", "medium", "low"],
        },
        "confidence_reason": {"type": "string"},
    },
    "required": ["description", "confidence", "confidence_reason"],
}


# Vision system prompt from CLAUDE.md. Shared across all vision providers and
# BOTH evidence kinds (still frames and video clips), so it is modality-neutral:
# "what is literally visible" (matching CLAUDE.md's canonical wording) rather
# than "in this image", which mislabeled video clips. The clip path additionally
# tells the model it's a video clip and to describe motion via the user message;
# for native-video providers (Gemini) that's where the temporal framing lives.
VISION_SYSTEM_PROMPT = """You are a clinical visual documentation assistant. Describe only what is literally visible. Do not diagnose, interpret, or infer clinical meaning.

Describe: patient position, visible body parts being examined, observable physical findings (swelling, redness, range of motion if measurable), equipment in use, screen content.
Do not describe: clinical meaning, what findings suggest, what should be done, anything not directly visible.

Return JSON only: {"description": "...", "confidence": "high|medium|low", "confidence_reason": "..."}
Confidence is LOW if: blurry, wrong angle, subject not clearly visible, no clinically relevant content visible."""


def parse_caption_json(provider_name: str, raw: str) -> dict:
    """Parse a provider's JSON response, raising ProviderError on failure.

    Catches ``json.JSONDecodeError`` (a ``ValueError`` subclass) and
    re-raises as ``ProviderError(provider_name, ...)`` so the registry's
    fallback chain in :func:`get_vision_provider_with_fallback` can trip
    cleanly. Without this wrapper, a truncated / malformed provider
    response leaks as a bare ``ValueError`` past the provider boundary —
    the Stage 2 dispatcher and the admin probe both classify that as a
    generic Python error rather than a provider failure, and the
    fallback chain never gets a turn.

    LSP boundary: every vision provider now emits the same error
    semantic on a malformed wire response, regardless of which SDK / API
    shape they're parsing.

    No PHI / no API keys are logged. The 120-char excerpt is the
    provider's own response (descriptive text generated by the model
    per ``VISION_SYSTEM_PROMPT``), not user content; defensively
    truncated so a runaway response can't bloat the log line and can't
    surface a malformed URL fragment past the cap.

    Args:
        provider_name: short provider identifier — ``"openai"``,
            ``"anthropic"``, ``"gemini"``. Used both as the
            ``ProviderError`` provider tag and as a label in the
            WARNING log.
        raw: the provider's response text, before any whitespace
            stripping. The helper does the strip itself so callers
            don't accidentally strip-and-pass a different shape.

    Returns:
        The parsed JSON object as a ``dict``.

    Raises:
        ProviderError: if the response is not valid JSON. The original
            ``json.JSONDecodeError`` is chained via ``raise ... from``
            for debugging.
    """
    try:
        return json.loads(raw.strip())
    except json.JSONDecodeError as exc:
        excerpt = raw[:_PARSE_FAILURE_LOG_LEN]
        logger.warning(
            "vision provider response JSON parse failed: provider=%s "
            "error=%s excerpt=%r",
            provider_name,
            type(exc).__name__,
            excerpt,
        )
        raise ProviderError(
            provider_name,
            f"response JSON parse failed: {type(exc).__name__}",
        ) from exc


def build_frame_caption(
    frame: MaskedFrame,
    anchor: TranscriptSegment,
    content: dict,
    provider_name: str,
) -> FrameCaption:
    """Build a FrameCaption from the parsed LLM response.

    All vision providers return the same caption structure -- only the
    ``provider_used`` field differs.
    """
    return FrameCaption(
        frame_id=frame.frame_id,
        session_id=frame.session_id,
        timestamp_ms=frame.timestamp_ms,
        audio_anchor_id=anchor.id,
        provider_used=provider_name,
        visual_description=content.get("description", ""),
        confidence=content.get("confidence", "medium"),
        confidence_reason=content.get("confidence_reason", ""),
        conflict_flag=False,
        conflict_detail=None,
        integration_status="ENRICHES",
    )
