"""Note export -- DOCX and plain text generation.

After export, triggers the cleanup pipeline to purge raw data and
migrate eval frames. Every export event is written to the audit trail.
"""

from __future__ import annotations

import io
import logging
from typing import Optional

from docx import Document
from docx.shared import Pt, RGBColor
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.types import Note
from app.modules.audit_log.service import get_audit_log_service
from app.modules.cleanup.service import (
    migrate_eval_frames,
    purge_frames,
)

logger = logging.getLogger("aurion.export")


async def export_note_docx(
    session_id: str,
    note: Note,
    db: AsyncSession,
) -> bytes:
    """Generate a DOCX document from a structured Note.

    Each note section becomes a heading. Claims within each section
    become body paragraphs with citation references. Sections with
    status ``not_captured`` or ``processing_failed`` are included with
    a status note.

    After generating the document, triggers the cleanup pipeline
    (frame purge and eval frame migration).

    Args:
        session_id: The session being exported.
        note: The approved Note to export.
        db: Database session (passed through for any transactional needs).

    Returns:
        The DOCX file content as bytes.
    """
    audit = get_audit_log_service()

    doc = Document()

    # ── Title ─────────────────────────────────────────────────────────
    title = doc.add_heading("Clinical Note", level=0)
    title_run = title.runs[0] if title.runs else title.add_run()
    title_run.font.color.rgb = RGBColor(0x0D, 0x1B, 0x3E)  # Aurion navy

    # ── Metadata paragraph ────────────────────────────────────────────
    meta = doc.add_paragraph()
    meta.add_run(f"Session: {note.session_id}").bold = True
    meta.add_run(f"  |  Specialty: {note.specialty}")
    meta.add_run(f"  |  Stage: {note.stage}")
    meta.add_run(f"  |  Version: {note.version}")
    meta.add_run(f"  |  Provider: {note.provider_used}")
    meta.add_run(f"  |  Completeness: {note.completeness_score:.0%}")

    doc.add_paragraph("")  # spacer

    # ── Sections ──────────────────────────────────────────────────────
    for section in note.sections:
        heading = doc.add_heading(section.title or section.id, level=1)
        heading_run = heading.runs[0] if heading.runs else heading.add_run()
        heading_run.font.color.rgb = RGBColor(0x0D, 0x1B, 0x3E)

        if section.status in ("not_captured", "processing_failed"):
            status_para = doc.add_paragraph()
            status_run = status_para.add_run(
                f"[{section.status.replace('_', ' ').title()}]"
            )
            status_run.italic = True
            status_run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)
            continue

        if not section.claims:
            status_para = doc.add_paragraph()
            status_run = status_para.add_run("[No claims recorded]")
            status_run.italic = True
            status_run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)
            continue

        for claim in section.claims:
            para = doc.add_paragraph()

            # Claim text
            claim_run = para.add_run(claim.text)
            claim_run.font.size = Pt(11)

            # Citation reference
            citation_run = para.add_run(
                f"  [{claim.source_type}: {claim.source_id}]"
            )
            citation_run.font.size = Pt(9)
            citation_run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)
            citation_run.italic = True

    # ── Footer ────────────────────────────────────────────────────────
    doc.add_paragraph("")
    footer_para = doc.add_paragraph()
    footer_run = footer_para.add_run(
        "Generated by Aurion Clinical AI. "
        "This document is a descriptive record of the clinical encounter."
    )
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)
    footer_run.italic = True

    # ── Serialize to bytes ────────────────────────────────────────────
    buffer = io.BytesIO()
    doc.save(buffer)
    docx_bytes = buffer.getvalue()

    logger.info(
        "DOCX exported: session=%s size=%d bytes",
        session_id,
        len(docx_bytes),
    )

    # ── Audit log ─────────────────────────────────────────────────────
    await audit.write_event(
        session_id=session_id,
        event_type="note_exported",
        format="docx",
        version=note.version,
        stage=note.stage,
    )

    # ── Trigger cleanup pipeline ──────────────────────────────────────
    try:
        await migrate_eval_frames(session_id)
    except Exception as exc:
        logger.error(
            "Eval frame migration failed during export cleanup: session=%s error=%s",
            session_id,
            str(exc),
        )
        # Non-fatal -- export still succeeds

    try:
        await purge_frames(session_id)
    except Exception as exc:
        logger.error(
            "Frame purge failed during export cleanup: session=%s error=%s",
            session_id,
            str(exc),
        )
        # Non-fatal -- export still succeeds

    return docx_bytes


def export_note_plaintext(session_id: str, note: Note) -> str:
    """Generate a plain text representation of a structured Note.

    This is the fallback export format when DOCX generation is not
    available (e.g., on-device iOS export).

    Args:
        session_id: The session being exported.
        note: The Note to export.

    Returns:
        The note as a plain text string.
    """
    lines: list[str] = []

    lines.append("CLINICAL NOTE")
    lines.append("=" * 60)
    lines.append(f"Session:      {note.session_id}")
    lines.append(f"Specialty:    {note.specialty}")
    lines.append(f"Stage:        {note.stage}")
    lines.append(f"Version:      {note.version}")
    lines.append(f"Provider:     {note.provider_used}")
    lines.append(f"Completeness: {note.completeness_score:.0%}")
    lines.append("")

    for section in note.sections:
        lines.append("-" * 60)
        lines.append(section.title or section.id)
        lines.append("-" * 60)

        if section.status in ("not_captured", "processing_failed"):
            lines.append(f"  [{section.status.replace('_', ' ').title()}]")
            lines.append("")
            continue

        if not section.claims:
            lines.append("  [No claims recorded]")
            lines.append("")
            continue

        for claim in section.claims:
            lines.append(f"  {claim.text}")
            lines.append(
                f"    [{claim.source_type}: {claim.source_id}]"
            )
        lines.append("")

    lines.append("=" * 60)
    lines.append(
        "Generated by Aurion Clinical AI. "
        "This document is a descriptive record of the clinical encounter."
    )

    text = "\n".join(lines)

    logger.info(
        "Plaintext exported: session=%s length=%d chars",
        session_id,
        len(text),
    )

    return text
