# =============================================================================
# Aurion Clinical AI — Terraform Root Configuration
# =============================================================================
# Replaces the AWS CDK TypeScript stack. Provisions all infrastructure for the
# Aurion MVP: VPC, ECS (Fargate + GPU), RDS PostgreSQL, DynamoDB, S3, Cognito,
# AppConfig, and CloudWatch monitoring.
# =============================================================================

terraform {
  # 1.7.0 introduced `removed` blocks; appconfig.tf uses them to detach
  # the InvalidSignatureException-cursed `aws_appconfig_hosted_configuration_version`
  # and `aws_appconfig_deployment.initial` resources from state without
  # destroying the live AWS resources. CI runs 1.9.0 so this isn't a CI
  # constraint — it's a guard for local devs running an older terraform.
  required_version = ">= 1.7.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  # -------------------------------------------------------------------------
  # S3 Remote State Backend
  # -------------------------------------------------------------------------
  # Partial backend config — values come from `backends/<env>.s3.tfbackend`,
  # generated by the bootstrap module's outputs. Initialize with:
  #
  #   terraform init -reconfigure -backend-config=backends/dev.s3.tfbackend
  #
  # See infrastructure/bootstrap/README.md for the one-time setup sequence.
  # -------------------------------------------------------------------------
  backend "s3" {}
}

# =============================================================================
# AWS Provider
# =============================================================================

provider "aws" {
  region = var.region

  default_tags {
    tags = {
      Project            = "aurion"
      Environment        = var.environment
      DataClassification = "phi-adjacent"
      ManagedBy          = "terraform"
    }
  }
}

# =============================================================================
# Data Sources
# =============================================================================

data "aws_caller_identity" "current" {}
data "aws_region" "current" {}
