# =============================================================================
# Outputs — Key resource identifiers for downstream use
# =============================================================================

# -----------------------------------------------------------------------------
# Networking
# -----------------------------------------------------------------------------

output "vpc_id" {
  description = "VPC ID"
  value       = aws_vpc.main.id
}

# -----------------------------------------------------------------------------
# ECS
# -----------------------------------------------------------------------------

output "ecs_cluster_arn" {
  description = "ECS Cluster ARN"
  value       = aws_ecs_cluster.main.arn
}

output "alb_url" {
  description = "FastAPI ALB URL"
  value       = "http://${aws_lb.api.dns_name}"
}

output "ecr_repository_url" {
  description = "ECR repository URL for backend Docker image"
  value       = aws_ecr_repository.backend.repository_url
}

# -----------------------------------------------------------------------------
# RDS
# -----------------------------------------------------------------------------

output "db_endpoint" {
  description = "RDS PostgreSQL endpoint"
  value       = aws_db_instance.main.endpoint
}

output "db_secret_arn" {
  description = "RDS credentials secret ARN (auto-generated by manage_master_user_password)"
  value       = aws_db_instance.main.master_user_secret[0].secret_arn
}

# -----------------------------------------------------------------------------
# DynamoDB
# -----------------------------------------------------------------------------

output "audit_log_table_name" {
  description = "DynamoDB audit log table name"
  value       = aws_dynamodb_table.audit_log.name
}

# -----------------------------------------------------------------------------
# S3
# -----------------------------------------------------------------------------

output "audio_bucket_name" {
  description = "S3 audio bucket name"
  value       = aws_s3_bucket.audio.id
}

output "frames_bucket_name" {
  description = "S3 frames bucket name"
  value       = aws_s3_bucket.frames.id
}

output "eval_bucket_name" {
  description = "S3 eval bucket name"
  value       = aws_s3_bucket.eval.id
}

# -----------------------------------------------------------------------------
# Cognito
# -----------------------------------------------------------------------------

output "cognito_user_pool_id" {
  description = "Cognito User Pool ID"
  value       = aws_cognito_user_pool.main.id
}

output "cognito_user_pool_client_id" {
  description = "Cognito User Pool Client ID"
  value       = aws_cognito_user_pool_client.main.id
}

# -----------------------------------------------------------------------------
# AppConfig
# -----------------------------------------------------------------------------

output "appconfig_application_id" {
  description = "AppConfig Application ID"
  value       = aws_appconfig_application.main.id
}

output "appconfig_environment_id" {
  description = "AppConfig Environment ID"
  value       = aws_appconfig_environment.main.environment_id
}

output "appconfig_profile_id" {
  description = "AppConfig Configuration Profile ID"
  value       = aws_appconfig_configuration_profile.main.configuration_profile_id
}

# -----------------------------------------------------------------------------
# KMS
# -----------------------------------------------------------------------------

output "kms_key_arn" {
  description = "KMS encryption key ARN"
  value       = aws_kms_key.main.arn
}

# -----------------------------------------------------------------------------
# CloudWatch
# -----------------------------------------------------------------------------

output "dashboard_url" {
  description = "CloudWatch Dashboard URL"
  value       = "https://${var.region}.console.aws.amazon.com/cloudwatch/home?region=${var.region}#dashboards:name=Aurion-${var.environment}"
}
