# =============================================================================
# Outputs — Key resource identifiers for downstream use
# =============================================================================

# -----------------------------------------------------------------------------
# Networking
# -----------------------------------------------------------------------------

output "vpc_id" {
  description = "VPC ID"
  value       = aws_vpc.main.id
}

# -----------------------------------------------------------------------------
# ECS
# -----------------------------------------------------------------------------

output "ecs_cluster_arn" {
  description = "ECS Cluster ARN"
  value       = aws_ecs_cluster.main.arn
}

output "alb_dns_name" {
  description = "Raw ALB DNS name (use `api_url` for the canonical, TLS-terminated URL)."
  value       = aws_lb.api.dns_name
}

output "api_url" {
  description = "Canonical HTTPS URL for the API (uses var.api_domain). Configure the iOS app's Config.swift BACKEND_URL with this."
  value       = "https://${var.api_domain}"
}

output "ecr_repository_url" {
  description = "ECR repository URL for backend Docker image"
  value       = aws_ecr_repository.backend.repository_url
}

# -----------------------------------------------------------------------------
# RDS
# -----------------------------------------------------------------------------

output "db_endpoint" {
  description = "RDS PostgreSQL endpoint"
  value       = aws_db_instance.main.endpoint
}

output "db_secret_arn" {
  description = "RDS credentials secret ARN (auto-generated by manage_master_user_password)"
  value       = aws_db_instance.main.master_user_secret[0].secret_arn
}

# -----------------------------------------------------------------------------
# DynamoDB
# -----------------------------------------------------------------------------

output "audit_log_table_name" {
  description = "DynamoDB audit log table name"
  value       = aws_dynamodb_table.audit_log.name
}

# -----------------------------------------------------------------------------
# S3
# -----------------------------------------------------------------------------

output "audio_bucket_name" {
  description = "S3 audio bucket name"
  value       = aws_s3_bucket.audio.id
}

output "frames_bucket_name" {
  description = "S3 frames bucket name"
  value       = aws_s3_bucket.frames.id
}

output "eval_bucket_name" {
  description = "S3 eval bucket name"
  value       = aws_s3_bucket.eval.id
}

# -----------------------------------------------------------------------------
# Cognito
# -----------------------------------------------------------------------------

output "cognito_user_pool_id" {
  description = "Cognito User Pool ID"
  value       = aws_cognito_user_pool.main.id
}

output "cognito_user_pool_client_id" {
  description = "Cognito User Pool Client ID"
  value       = aws_cognito_user_pool_client.main.id
}

output "cognito_hosted_ui_domain" {
  description = "Hosted UI base URL for Cognito (sign-in lives at /login, signout at /logout). iOS Config.swift COGNITO_HOSTED_UI_BASE."
  value       = "https://${aws_cognito_user_pool_domain.main.domain}.auth.${var.region}.amazoncognito.com"
}

# -----------------------------------------------------------------------------
# AppConfig
# -----------------------------------------------------------------------------

output "appconfig_application_id" {
  description = "AppConfig Application ID"
  value       = aws_appconfig_application.main.id
}

output "appconfig_environment_id" {
  description = "AppConfig Environment ID"
  value       = aws_appconfig_environment.main.environment_id
}

output "appconfig_profile_id" {
  description = "AppConfig Configuration Profile ID"
  value       = aws_appconfig_configuration_profile.main.configuration_profile_id
}

# -----------------------------------------------------------------------------
# KMS
# -----------------------------------------------------------------------------

output "kms_key_arn" {
  description = "KMS encryption key ARN"
  value       = aws_kms_key.main.arn
}

# -----------------------------------------------------------------------------
# CloudWatch
# -----------------------------------------------------------------------------

output "dashboard_url" {
  description = "CloudWatch Dashboard URL"
  value       = "https://${var.region}.console.aws.amazon.com/cloudwatch/home?region=${var.region}#dashboards:name=Aurion-${var.environment}"
}

# -----------------------------------------------------------------------------
# DNS + TLS + WAF (Phase 2)
# -----------------------------------------------------------------------------

output "route53_zone_id" {
  description = "Hosted zone ID for the apex domain. Same value whether this env owns the zone or reads it via data source."
  value       = local.route53_zone_id
}

output "route53_nameservers" {
  description = "NS records to set at the domain registrar after the first `terraform apply` in the owning env. Until these are delegated, ACM cert validation will hang. Example: copy these 4 values into the NS section for `aurionclinical.com` at your registrar."
  value       = local.route53_nameservers
}

output "acm_certificate_arn" {
  description = "ARN of the ACM cert for var.api_domain. Wired into the ALB HTTPS listener."
  value       = aws_acm_certificate_validation.api.certificate_arn
}

output "waf_web_acl_arn" {
  description = "WAFv2 web ACL ARN — associated with the ALB."
  value       = aws_wafv2_web_acl.api.arn
}

# -----------------------------------------------------------------------------
# GitHub Actions OIDC (Phase 3)
# -----------------------------------------------------------------------------

output "github_deployer_dev_role_arn" {
  description = "ARN of the IAM role GitHub Actions assumes on pushes to main. Set this as the `AWS_DEPLOY_ROLE_DEV` repo secret."
  value       = aws_iam_role.github_deployer_dev.arn
}

output "github_deployer_prod_role_arn" {
  description = "ARN of the IAM role GitHub Actions assumes for manual prod deploys (workflow_dispatch in the `prod` environment). Set this as the `AWS_DEPLOY_ROLE_PROD` repo secret."
  value       = aws_iam_role.github_deployer_prod.arn
}

output "ecr_registry" {
  description = "ECR registry hostname (account-id.dkr.ecr.region.amazonaws.com). Set as the `ECR_REGISTRY` repo secret."
  value       = split("/", aws_ecr_repository.backend.repository_url)[0]
}

# -----------------------------------------------------------------------------
# Phase 4 — observability + audit
# -----------------------------------------------------------------------------

output "alerts_sns_topic_arn" {
  description = "SNS topic every CloudWatch alarm publishes to. Subscribe additional endpoints (PagerDuty, Slack, etc.) via the AWS console."
  value       = aws_sns_topic.alerts.arn
}

output "audit_logs_bucket" {
  description = "Bucket holding CloudTrail + VPC Flow Logs + S3 access logs. 7-year retention, Glacier transition after 90d."
  value       = aws_s3_bucket.audit_logs.id
}

output "cloudtrail_name" {
  description = "Multi-region CloudTrail name."
  value       = aws_cloudtrail.main.name
}

# -----------------------------------------------------------------------------
# W010 — Web Portal (Amplify)
# -----------------------------------------------------------------------------

output "portal_url" {
  description = "Custom HTTPS URL for the web admin portal (custom-domain path). Reachable once 4 NS records are added at Cloudflare for var.web_portal_subdomain — see `portal_nameservers`. Until then, use `amplify_default_url`."
  value       = "https://${var.web_portal_subdomain}"
}

output "portal_nameservers" {
  description = "NS records to set at Cloudflare for var.web_portal_subdomain after the first apply. Same delegation pattern as route53_nameservers — add 4 NS records at Cloudflare for the portal subdomain pointing at these AWS nameservers, then ACM + Amplify domain verification can complete. Custom domain becomes reachable ~30-60 min after DNS propagation."
  value       = aws_route53_zone.portal.name_servers
}

output "amplify_app_id" {
  description = "Amplify app ID — needed for CLI deploys (`aws amplify create-deployment --app-id <ID>`), dashboard URLs, and the GitHub Actions `AMPLIFY_APP_ID` repo variable."
  value       = aws_amplify_app.web_portal.id
}

output "amplify_default_url" {
  description = "Amplify-managed default URL (https://main.<APP_ID>.amplifyapp.com). Works immediately after the first deploy without custom domain. Add this to the Cognito client callback list to unblock OAuth login on the default URL — see docs/dev/web-deploy.md for the CLI one-liner."
  value       = "https://${aws_amplify_branch.main.branch_name}.${aws_amplify_app.web_portal.default_domain}"
}
