# =============================================================================
# Outputs — Key resource identifiers for downstream use
# =============================================================================

# -----------------------------------------------------------------------------
# Networking
# -----------------------------------------------------------------------------

output "vpc_id" {
  description = "VPC ID"
  value       = aws_vpc.main.id
}

# -----------------------------------------------------------------------------
# ECS
# -----------------------------------------------------------------------------

output "ecs_cluster_arn" {
  description = "ECS Cluster ARN"
  value       = aws_ecs_cluster.main.arn
}

output "alb_dns_name" {
  description = "Raw ALB DNS name (use `api_url` for the canonical, TLS-terminated URL)."
  value       = aws_lb.api.dns_name
}

output "api_url" {
  description = "Canonical HTTPS URL for the API (uses var.api_domain). Configure the iOS app's Config.swift BACKEND_URL with this."
  value       = "https://${var.api_domain}"
}

output "ecr_repository_url" {
  description = "ECR repository URL for backend Docker image"
  value       = aws_ecr_repository.backend.repository_url
}

# -----------------------------------------------------------------------------
# RDS
# -----------------------------------------------------------------------------

output "db_endpoint" {
  description = "RDS PostgreSQL endpoint"
  value       = aws_db_instance.main.endpoint
}

output "db_secret_arn" {
  description = "RDS credentials secret ARN (auto-generated by manage_master_user_password)"
  value       = aws_db_instance.main.master_user_secret[0].secret_arn
}

# -----------------------------------------------------------------------------
# DynamoDB
# -----------------------------------------------------------------------------

output "audit_log_table_name" {
  description = "DynamoDB audit log table name"
  value       = aws_dynamodb_table.audit_log.name
}

# -----------------------------------------------------------------------------
# S3
# -----------------------------------------------------------------------------

output "audio_bucket_name" {
  description = "S3 audio bucket name"
  value       = aws_s3_bucket.audio.id
}

output "frames_bucket_name" {
  description = "S3 frames bucket name"
  value       = aws_s3_bucket.frames.id
}

output "eval_bucket_name" {
  description = "S3 eval bucket name"
  value       = aws_s3_bucket.eval.id
}

# -----------------------------------------------------------------------------
# Cognito
# -----------------------------------------------------------------------------

output "cognito_user_pool_id" {
  description = "Cognito User Pool ID"
  value       = aws_cognito_user_pool.main.id
}

output "cognito_user_pool_client_id" {
  description = "Cognito User Pool Client ID"
  value       = aws_cognito_user_pool_client.main.id
}

# -----------------------------------------------------------------------------
# AppConfig
# -----------------------------------------------------------------------------

output "appconfig_application_id" {
  description = "AppConfig Application ID"
  value       = aws_appconfig_application.main.id
}

output "appconfig_environment_id" {
  description = "AppConfig Environment ID"
  value       = aws_appconfig_environment.main.environment_id
}

output "appconfig_profile_id" {
  description = "AppConfig Configuration Profile ID"
  value       = aws_appconfig_configuration_profile.main.configuration_profile_id
}

# -----------------------------------------------------------------------------
# KMS
# -----------------------------------------------------------------------------

output "kms_key_arn" {
  description = "KMS encryption key ARN"
  value       = aws_kms_key.main.arn
}

# -----------------------------------------------------------------------------
# CloudWatch
# -----------------------------------------------------------------------------

output "dashboard_url" {
  description = "CloudWatch Dashboard URL"
  value       = "https://${var.region}.console.aws.amazon.com/cloudwatch/home?region=${var.region}#dashboards:name=Aurion-${var.environment}"
}

# -----------------------------------------------------------------------------
# DNS + TLS + WAF (Phase 2)
# -----------------------------------------------------------------------------

output "route53_zone_id" {
  description = "Hosted zone ID for the apex domain. Same value whether this env owns the zone or reads it via data source."
  value       = local.route53_zone_id
}

output "route53_nameservers" {
  description = "NS records to set at the domain registrar after the first `terraform apply` in the owning env. Until these are delegated, ACM cert validation will hang. Example: copy these 4 values into the NS section for `aurionclinical.com` at your registrar."
  value       = local.route53_nameservers
}

output "acm_certificate_arn" {
  description = "ARN of the ACM cert for var.api_domain. Wired into the ALB HTTPS listener."
  value       = aws_acm_certificate_validation.api.certificate_arn
}

output "waf_web_acl_arn" {
  description = "WAFv2 web ACL ARN — associated with the ALB."
  value       = aws_wafv2_web_acl.api.arn
}
